export const CHANGE_PRODUCT = 'CHANGE_PRODUCT'
export const CHANGE_MODAL_STATE = 'CHANGE_MODAL_STATE'
export const SET_MODAL_ADD_OR_DEL_VALUE = 'SET_MODAL_ADD_OR_DEL_VALUE'
export const SET_MODAL_HEADER = 'SET_MODAL_HEADER'
