export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const LOAD_ITEMS_TO_CART = 'LOAD_ITEMS_TO_CART';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
